name: Java Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # You can adjust the OS if needed

    steps:
    - name: Check Java Availability
      run: java -version

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Print JAVA_HOME
      run: echo $JAVA_HOME

    - name: List Directory Contents
      run: ls -la

    - name: Run Java Command
      run: $JAVA_HOME/bin/java -version  # Modify this based on your actual Java command

    - name: Checkout Code
      uses: actions/checkout@v2
